version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: astro_user
      POSTGRES_PASSWORD: astro_pass
      POSTGRES_DB: astrodb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass cache_pass
    restart: always
    environment:
    - REDIS_PASSWORD=cache_pass
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: impl/Dockerfile
    container_name: astroapi
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  ui:
    build: ./ui
    container_name: astroui
    restart: always
    depends_on: 
      - api
    ports:
    - "3000:80"

volumes:
  postgres_data:
