database:
  host: postgres
  name: astrodb
  port: 5432
  user: astro_user
  password: astro_pass
  performance:
    batchsize: 100
datasource:
  file: /app/data/PSCompPars_2025.03.06_19.24.17.csv
  exoplanet_data:
    name: pl_name
    host: hostname
    mass: pl_bmasse
    radius: pl_rade
    dist: pl_orbsmax

