database:
  host: postgres
  name: astrodb
  port: 5432
  user: astro_user
  password: astro_pass
  performance:
    batch_size: 100
    max_retries: 5
    retry_interval: 1
api:
  jwk_path: /app/conf/jwk.json
logger:
  log_level: INFO
  log_file: /app/logs/astroapi.log
cache: 
  host: redis
  port: 6379
  password: cache_pass
  performance:
    expiry: 60
    max_retries: 5
    retry_interval: 1
datasource:
  file: /app/data/PSCompPars_2025.03.06_19.24.17.csv
  exoplanet_data:
    name: 
      column: pl_name
    host: 
      column: hostname
    mass:
      column: pl_bmasse
      unit: Earth mass
    radius:  
      column: pl_rade
      unit: Earth radius
    dist:  
      column: pl_orbsmax
      unit: AU
  star_data:
    name:  
      column: hostname
    mass:  
      column: st_mass
      unit: Sun mass
    radius:  
      column: st_rad
      unit: Sun radius
    temp:  
      column: st_teff
      unit: K
