database:
  host: postgres
  name: astrodb
  port: 5432
  user: astro_user
  password: astro_pass
  performance:
    batch_size: 100
    max_retries: 5
    retry_interval: 1
datasource:
  file: /app/data/PSCompPars_2025.03.06_19.24.17.csv
  exoplanet_data:
    name: pl_name
    host: hostname
    mass: pl_bmasse
    radius: pl_rade
    dist: pl_orbsmax
  star_data:
    name: hostname
    mass: st_mass
    radius: st_rad
    temp: st_teff
